definitions:
  model.StGrafanaAlert:
    properties:
      dashboardId:
        type: integer
      evalMatches:
        items:
          $ref: '#/definitions/model.stEvalMatch'
        type: array
      imageUrl:
        type: string
      message:
        type: string
      orgId:
        type: integer
      panelId:
        type: integer
      ruleId:
        type: integer
      ruleName:
        type: string
      ruleUrl:
        type: string
      state:
        type: string
      tags:
        additionalProperties:
          type: string
        type: object
      title:
        type: string
    type: object
  model.StPublicProducerMail:
    properties:
      cc:
        items:
          type: string
        type: array
      content:
        type: string
      from:
        type: string
      producer:
        example: wiss or wingo or kiss or more
        type: string
      title:
        type: string
      to:
        items:
          type: string
        type: array
    required:
    - content
    - from
    - producer
    - title
    - to
    type: object
  model.StPublicProducerTeams:
    properties:
      content:
        type: string
      from:
        type: string
      producer:
        example: wiss or wingo or kiss or more
        type: string
      title:
        type: string
      touri:
        example: http://xxx.x.xx.xxx.x.
        type: string
    required:
    - content
    - from
    - producer
    - title
    - touri
    type: object
  model.stEvalMatch:
    properties:
      metric:
        type: string
      tags:
        $ref: '#/definitions/model.stEvalMatchTags'
      value:
        type: integer
    type: object
  model.stEvalMatchTags:
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - application/json
      description: notifyhandler server heath check
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: site health check is running will return "working!"
  /v1/grafana/mail:
    post:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      parameters:
      - description: json struct for send mail
        in: body
        name: jsonbody
        required: true
        schema:
          $ref: '#/definitions/model.StGrafanaAlert'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 'Grafana mail api  : have just post api'
  /v1/grafana/teams:
    post:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      parameters:
      - description: json struct for send teams
        in: body
        name: jsonbody
        required: true
        schema:
          $ref: '#/definitions/model.StGrafanaAlert'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 'Grafana teams api  : have just post api'
  /v1/public/mail:
    post:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      parameters:
      - description: json struct for send mail
        in: body
        name: jsonbody
        required: true
        schema:
          $ref: '#/definitions/model.StPublicProducerMail'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 'public mail api  : have just post api'
  /v1/public/teams:
    post:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      parameters:
      - description: json struct for send teams
        in: body
        name: jsonbody
        required: true
        schema:
          $ref: '#/definitions/model.StPublicProducerTeams'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 'Grafana teams api  : have just post api'
swagger: "2.0"
