info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: site health check is running will return "working!"
  /v1/health:
    get:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 써머리를 직접 수정했습니다
  /v1/login:
    post:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 써머리를 직접 수정했습니다
  /v1/param/{test}/{action}:
    get:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      parameters:
      - description: test
        in: path
        name: test
        required: true
        type: string
      - description: action
        in: path
        name: action
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 써머리를 직접 수정했습니다
  /v1/signup:
    post:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 써머리를 직접 수정했습니다
swagger: "2.0"
