info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 써머리를 직접 수정했습니다
  /login:
    post:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 써머리를 직접 수정했습니다
  /signup:
    post:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 써머리를 직접 수정했습니다
swagger: "2.0"
