info:
  contact: {}
paths:
  /v1/{name}:
    get:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      parameters:
      - description: User name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 써머리를 직접 수정했습니다
swagger: "2.0"
